INSERT INTO rating (ORD_ID,RAT_RATSTARS)VALUES
((SELECT ORD_ID FROM `ORDER` WHERE ORD_AMOUNT = 1500),4),
((SELECT ORD_ID FROM `ORDER` WHERE ORD_AMOUNT = 1000),3),
((SELECT ORD_ID FROM `ORDER` WHERE ORD_AMOUNT = 30000),1),
((SELECT ORD_ID FROM `ORDER` WHERE ORD_AMOUNT = 15000),2),
((SELECT ORD_ID FROM `ORDER` WHERE ORD_AMOUNT = 3000),4),
((SELECT ORD_ID FROM `ORDER` WHERE ORD_AMOUNT = 1450),3),
((SELECT ORD_ID FROM `ORDER` WHERE ORD_AMOUNT = 789),4),
((SELECT ORD_ID FROM `ORDER` WHERE ORD_AMOUNT = 780),4),
((SELECT ORD_ID FROM `ORDER` WHERE ORD_AMOUNT = 3001),3),
((SELECT ORD_ID FROM `ORDER` WHERE ORD_AMOUNT = 2500),5),
((SELECT ORD_ID FROM `ORDER` WHERE ORD_AMOUNT = 10000),3),
((SELECT ORD_ID FROM `ORDER` WHERE ORD_AMOUNT = 781),4),
((SELECT ORD_ID FROM `ORDER` WHERE ORD_AMOUNT = 31000),2),
((SELECT ORD_ID FROM `ORDER` WHERE ORD_AMOUNT = 1001),1),
((SELECT ORD_ID FROM `ORDER` WHERE ORD_AMOUNT = 3002),1),
((SELECT ORD_ID FROM `ORDER` WHERE ORD_AMOUNT = 99),0);











